name: Build and Publish Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv sync
      - name: Build package
        run: |
          uv build
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
